version: '3.8'

services:
  mariadb:
    image: mariadb:11
    container_name: maets_mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: maets
      MARIADB_USER: maets_user
      MARIADB_PASSWORD: maets_pass
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  mongodb:
    image: mongo:7
    container_name: maets_mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mariadb_data:
  mongo_data:
